---
title: About
format: 
  html:
    page-layout: article
title-block-banner: true
---

::: {.column-margin}

```{r}
#| echo: false
#| warning: false
source("art.R")
home_art
```
:::

::: {.display-1 .fs-2 .fw-normal}
Bridge2Food Research is the research and industry intelligence arm of Bridge2Food
:::

::: {.display-2 .fs-4 .fw-light}
We address global food and agriculture challenges by bridging knowledge gaps between industry, academia, and policy to:

-   Facilitate evidence-based decisions and policy-making processes
-   Accelerate the development and implementation of high-impact technologies
-   Raise standards for how science is communicated and harnessed

Through the provision of information, data, and analysis, Bridge2Food Research helps establish rigorous baselines for understanding complex, multifaceted topics. By doing so, we foster public and private sector alignment with scientific knowledge, while bringing to light untapped opportunities for collaboration and problem solving at scale.
:::
