---
title: "Plant Protein Upstream Supplier Survey"
format: dashboard
scrolling: true
include-in-header:
  text: |
    <link rel="shortcut icon" href="/assets/images/logos/b2flogo.png" />
    <link rel="icon" type="image/x-icon" href="/assets/images/logos/favicon.ico">
    <link rel="stylesheet" type="text/css" href="styles.css">
---

```{r}
source("ppus.R")
source("bcs.R")
```

# Summary

## Row {height="220px"}

### Column

::: {.valuebox icon="bar-chart-line" color="secondary" title="Industry Confidence"}

`r curr_ic`

<i class="bi bi-`r caret(curr_ic_dq)` `r caret_color(curr_ic_dq)`"></i> `r curr_ic_dq` &nbsp;&nbsp; <i class="bi bi-`r caret(curr_ic_pdq)` `r caret_color(curr_ic_pdq)`"></i> `r curr_ic_pdq`
:::


### Column

```{r}
#| content: valuebox
#| title: "Economic Uncertainty"

list(
  icon = "triangle",
  color = "secondary",
  value = sprintf("%.2f", round(curr_iu, 2))
)
```

### Column

```{r}
#| content: valuebox
#| title: "Employment Outlook"

list(
  icon = "people",
  color = "light",
  value = sprintf("%.2f", round(curr_eo, 2))
)
```

## Row

### Column
```{r}
#| title: "Business Uncertainty"
uncertainty_bar
```

### Column
```{r}
#| title: "3-Year Business Plans"
plans_pie
```
## Row

### Column
```{r}
#| title: "Competitive Position"
comp_past_3_pie
```

### Column
```{r}
#| title: "Regional Sales Distribution"
regions_dist_donut
```

## Row

### Column

```{r}
#| title: "Industry Confidence"
bcs_cof
```


# Production & Orders

## Row

```{r}
#| title: "Recent Orders"
orders_past_3_pie
```

```{r}
#| title: "Current Order Books"
orders_curr_pie
```

## Row

```{r}
#| title: "Production Level"
prod_lvl_box
```

```{r}
#| title: "Production Capacity"
prod_cap_bar
```

## Row

```{r}
#| title: "Current Stocks of Finished Products"
stocks_curr_pie
```

## Row

### Column {.tabset}

```{r}
#| title: "Production - Past 3 Months"
prod_past_3_pie
```

```{r}
#| title: "Euro Area Historical"
bcs_m_ea_prod_trend
```

### Column

```{r}
#| title: "Production Expectations - Next 3 Months"
prod_next_3_pie
```



## Row

```{r}
#| title: "Factors Limiting Production"
prod_limits_pie
```

# Inputs & Prices

## Row

```{r}
#| title: "Input Costs (Excluding Labour) - Past 3 Months"
costs_past_3_pie
```

```{r}
#| title: "Expected Input Costs (Excluding Labour) - Next 3 Months"
costs_next_3_pie
```

## Row

```{r}
#| title: "Selling Prices - Past 3 Months"
prices_past_3_pie
```

```{r}
#| title: "Expected Selling Prices - Next 3 Months"
prices_next_3_pie
```   

# Labour

## Row

```{r}
#| title: "Staff Numbers - Past 3 Months"
emp_past_3_pie
```

```{r}
#| title: "Expected Staff Numbers - Next 3 Months"
emp_next_3_pie
``` 

## Row

```{r}
#| title: "Labour Costs - Past 3 Months"
lab_costs_past_3_pie
```
```{r}
#| title: "Labour Costs"
lab_costs_lvl_pie
```

## Row

```{r}
#| title: "Finding Skilled Labour"
lab_skill_pie
```


# Investment & Innovation

## Row

```{r}
#| title: "Investments - Past 3 Months"
inv_past_3_bar
```

## Row

