---
title: Methodology Notes
format: 
  html:
    page-layout: article
title-block-banner: true
---

::: fs-4
This page outlines key methodology details and explains differences from the Joint Harmonised EU Programme of Business and Consumer Surveys.
:::

# Aggregation Level

The [Joint Harmonised EU Programme of Business and Consumer Surveys](https://economy-finance.ec.europa.eu/economic-forecast-and-surveys/business-and-consumer-surveys_en) (BCS programme) provides industry data and composite indicators at the [NACE Rev. 2.1](https://showvoc.op.europa.eu/#/datasets/ESTAT_Statistical_Classification_of_Economic_Activities_in_the_European_Community_Rev._2.1._%28NACE_2.1%29/data) two-digit level, where Division 10 represents the manufacture of food products. At the three-digit level, Group 10.1 represents the production of meat products, while Group 10.5 represents the manufacture of dairy products. At the four-digit level of the NACE taxonomy, plant-based meat and milk substitutes fall under Class 10.89, which broadly represents the "manufacture of other food products not elsewhere classified".

While the BCS programme's surveys of industry do not provide disaggregated data for Groups 10.1 and 10.5, several economic indicators are available to monitor the status of these sectors, such as producer and consumer prices, and livestock and dairy futures, among others. In contrast, no such figures are available for plant-derived analogs of those sectors' products.

Bridge2Food's (B2F) industry surveys provide data for the plant-based meat and dairy substitute sectors that are directly comparable to BCS programme figures for the food industry. These data also serve to benchmark the plant protein sector over time and against other food and technology segments.

# Frequency

The BCS programme's industry surveys are conducted monthly, with different questionnaires sent out on a quarterly basis. B2F industry surveys combine questions from the BCS programme's monthly and quarterly industry surveys into a single quarterly questionnaire. Additionally, both BCS programme and B2F industry surveys include extra questions in Q2 and Q4 regarding experiences from the previous and current year, as well as expectations for the upcoming year.

# Geography

The BCS programme's industry surveys focus exclusively on the European regional economy. B2F industry surveys are not geographically limited and include respondents from all continents and regions. For instance, the BCS programme's industry surveys include questions on export orders and competitive positions in foreign markets inside and outside the EU. Since B2F industry surveys are not geographically constrained, these questions are excluded. Instead, B2F surveys include questions about geographic sales distributions, intended to highlight the relative significance of regional markets within the sector of the survey's focus.

# Seasonal Adjustment

Typically, data must be collected for at least three years before applying seasonal adjustments. The BCS programme's industry survey data are available as both seasonally adjusted and non-seasonally adjusted figures. Currently, B2F industry survey data are only available as non-seasonally adjusted.

# Language, Phrasing, and Data Collection

The BCS programme's industry surveys are conducted in the languages of the respondent countries and may be carried out in different formats, including via telephone interview. B2F industry surveys are conducted solely in English via the web-based survey software Qualtrics. While the core meaning of each question remains harmonised with the BCS programme's industry surveys, the phrasing of some B2F survey questions may vary slightly to optimise presentation and clarity in written format.

# Labour

B2F industry surveys include questions about labour that are not present in BCS programme surveys. These cover topics such as labour costs and the availability of skilled workers, offering deeper insights into the sector's labour supply and demand dynamics.

# Pre-Market Segments

In addition to industry surveys of the plant protein sector, whose methodologies closely align with those of the BCS programme's industry surveys, B2F conducts surveys of emerging protein technology sectors, investors, and industry analysts. These surveys are also designed to provide macro-level insight into their respective fields; however, they focus more on R&D activities and respondent sentiment rather than standard market indicators.

# Resources

The BCS programme's industry survey and reporting methodologies are detailed in the BCS User Guide, national questionnaires, and other documents available on the website of the [Directorate General for Economic and Financial Affairs](https://economy-finance.ec.europa.eu/economic-forecast-and-surveys/business-and-consumer-surveys/methodology-business-and-consumer-surveys_en).

View a B2F industry survey [example questionnaire](https://qualtricsxmgtnmmghg4.eu.qualtrics.com/jfe8/preview/previewId/ed37fae6-1514-4486-965a-6fe7b8df4ceb/SV_8A34lhRLUqBdIr4?Q_CHL=preview&Q_SurveyVersionID=current&Q_ShowMobile=0&Q_Loader=0). Note: this is for informal reference only. Data submitted via this form will not be collected. Actual industry survey questionnaires may vary from this example.

B2F survey data aggregation and visualisation code is publicly available on [GitHub](https://github.com/bridge2food/research/tree/main/data/dashboards).

For questions or additional clarifications, please email research@bridge2food.com.
